create extension if not exists "pgcrypto";

create type public.demanda_status as enum ('aberto', 'em_andamento', 'concluido', 'cancelado');
create type public.notification_type as enum ('demanda', 'aviso', 'processo');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.areas (
  id text primary key,
  nome text not null,
  descricao text not null,
  icon text not null,
  cor text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.demandas (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text,
  area_id text references public.areas(id) on delete set null,
  status public.demanda_status not null default 'aberto',
  user_id uuid not null references auth.users(id) on delete cascade,
  assignee_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.avisos (
  id uuid primary key default gen_random_uuid(),
  titulo text not null,
  resumo text not null,
  autor text not null,
  destaque boolean not null default false,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.processos (
  id uuid primary key default gen_random_uuid(),
  titulo text not null,
  descricao text,
  area_id text references public.areas(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  last_accessed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text not null,
  type public.notification_type not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.demanda_attachments (
  id uuid primary key default gen_random_uuid(),
  demanda_id bigint not null references public.demandas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  bucket_id text not null default 'demandas',
  storage_path text not null,
  filename text not null,
  content_type text,
  size_bytes bigint,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

create trigger areas_set_updated_at
  before update on public.areas
  for each row execute function public.set_updated_at();

create trigger demandas_set_updated_at
  before update on public.demandas
  for each row execute function public.set_updated_at();

create trigger avisos_set_updated_at
  before update on public.avisos
  for each row execute function public.set_updated_at();

create trigger processos_set_updated_at
  before update on public.processos
  for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update
    set full_name = excluded.full_name,
        avatar_url = excluded.avatar_url,
        updated_at = now();
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.areas enable row level security;
alter table public.demandas enable row level security;
alter table public.avisos enable row level security;
alter table public.processos enable row level security;
alter table public.notifications enable row level security;
alter table public.demanda_attachments enable row level security;

create policy "Profiles are readable by authenticated users"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Areas are readable by authenticated users"
  on public.areas for select
  to authenticated
  using (true);

create policy "Avisos are readable by authenticated users"
  on public.avisos for select
  to authenticated
  using (true);

create policy "Users can read their own demandas"
  on public.demandas for select
  to authenticated
  using (auth.uid() = user_id or auth.uid() = assignee_id);

create policy "Users can create their own demandas"
  on public.demandas for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update their own demandas"
  on public.demandas for update
  to authenticated
  using (auth.uid() = user_id or auth.uid() = assignee_id)
  with check (auth.uid() = user_id or auth.uid() = assignee_id);

create policy "Users can delete their own demandas"
  on public.demandas for delete
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can read related processos"
  on public.processos for select
  to authenticated
  using (user_id is null or auth.uid() = user_id);

create policy "Users can create their own processos"
  on public.processos for insert
  to authenticated
  with check (user_id is null or auth.uid() = user_id);

create policy "Users can update their own processos"
  on public.processos for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read their own notifications"
  on public.notifications for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can update their own notifications"
  on public.notifications for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read attachments for accessible demandas"
  on public.demanda_attachments for select
  to authenticated
  using (
    exists (
      select 1
      from public.demandas d
      where d.id = demanda_attachments.demanda_id
        and (d.user_id = auth.uid() or d.assignee_id = auth.uid())
    )
  );

create policy "Users can create attachments for their own demandas"
  on public.demanda_attachments for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and exists (
      select 1
      from public.demandas d
      where d.id = demanda_attachments.demanda_id
        and d.user_id = auth.uid()
    )
  );

insert into storage.buckets (id, name, public)
values ('demandas', 'demandas', false)
on conflict (id) do nothing;

create policy "Authenticated users can upload demanda files"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'demandas' and owner = auth.uid());

create policy "Authenticated users can read own demanda files"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'demandas' and owner = auth.uid());

create policy "Authenticated users can update own demanda files"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'demandas' and owner = auth.uid())
  with check (bucket_id = 'demandas' and owner = auth.uid());

create policy "Authenticated users can delete own demanda files"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'demandas' and owner = auth.uid());

alter publication supabase_realtime add table public.demandas;
alter publication supabase_realtime add table public.avisos;
alter publication supabase_realtime add table public.notifications;
alter publication supabase_realtime add table public.processos;

insert into public.areas (id, nome, descricao, icon, cor) values
  ('rh', 'Recursos Humanos', 'Pessoas, beneficios e carreira', 'Users', 'oklch(0.62 0.18 268)'),
  ('ti', 'Tecnologia', 'Suporte, sistemas e infraestrutura', 'Briefcase', 'oklch(0.52 0.18 265)'),
  ('fin', 'Financeiro', 'Reembolsos, pagamentos e notas', 'Wallet', 'oklch(0.69 0.14 165)'),
  ('atend', 'Atendimento', 'SAC e suporte ao cliente', 'Headphones', 'oklch(0.78 0.15 75)'),
  ('mkt', 'Marketing', 'Campanhas e comunicacao interna', 'Megaphone', 'oklch(0.6 0.22 27)'),
  ('comp', 'Compliance', 'Auditoria, riscos e LGPD', 'ShieldCheck', 'oklch(0.42 0.12 290)')
on conflict (id) do update
  set nome = excluded.nome,
      descricao = excluded.descricao,
      icon = excluded.icon,
      cor = excluded.cor,
      updated_at = now();
