/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProcessosRouteImport } from './routes/_authenticated/processos'
import { Route as AuthenticatedDemandasRouteImport } from './routes/_authenticated/demandas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBuscaRouteImport } from './routes/_authenticated/busca'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedAreasNovaRouteImport } from './routes/_authenticated/areas.nova'
import { Route as AuthenticatedAreasSlugRouteImport } from './routes/_authenticated/areas.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProcessosRoute = AuthenticatedProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandasRoute = AuthenticatedDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBuscaRoute = AuthenticatedBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAreasNovaRoute = AuthenticatedAreasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedAreasRoute,
} as any)
const AuthenticatedAreasSlugRoute = AuthenticatedAreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedAreasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/areas': typeof AuthenticatedAreasRouteWithChildren
  '/busca': typeof AuthenticatedBuscaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRoute
  '/processos': typeof AuthenticatedProcessosRoute
  '/areas/$slug': typeof AuthenticatedAreasSlugRoute
  '/areas/nova': typeof AuthenticatedAreasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/areas': typeof AuthenticatedAreasRouteWithChildren
  '/busca': typeof AuthenticatedBuscaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRoute
  '/processos': typeof AuthenticatedProcessosRoute
  '/areas/$slug': typeof AuthenticatedAreasSlugRoute
  '/areas/nova': typeof AuthenticatedAreasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRouteWithChildren
  '/_authenticated/busca': typeof AuthenticatedBuscaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demandas': typeof AuthenticatedDemandasRoute
  '/_authenticated/processos': typeof AuthenticatedProcessosRoute
  '/_authenticated/areas/$slug': typeof AuthenticatedAreasSlugRoute
  '/_authenticated/areas/nova': typeof AuthenticatedAreasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/areas'
    | '/busca'
    | '/configuracoes'
    | '/dashboard'
    | '/demandas'
    | '/processos'
    | '/areas/$slug'
    | '/areas/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/areas'
    | '/busca'
    | '/configuracoes'
    | '/dashboard'
    | '/demandas'
    | '/processos'
    | '/areas/$slug'
    | '/areas/nova'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/areas'
    | '/_authenticated/busca'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/demandas'
    | '/_authenticated/processos'
    | '/_authenticated/areas/$slug'
    | '/_authenticated/areas/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/processos': {
      id: '/_authenticated/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof AuthenticatedProcessosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandas': {
      id: '/_authenticated/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AuthenticatedDemandasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/busca': {
      id: '/_authenticated/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof AuthenticatedBuscaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/areas/nova': {
      id: '/_authenticated/areas/nova'
      path: '/nova'
      fullPath: '/areas/nova'
      preLoaderRoute: typeof AuthenticatedAreasNovaRouteImport
      parentRoute: typeof AuthenticatedAreasRoute
    }
    '/_authenticated/areas/$slug': {
      id: '/_authenticated/areas/$slug'
      path: '/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AuthenticatedAreasSlugRouteImport
      parentRoute: typeof AuthenticatedAreasRoute
    }
  }
}

interface AuthenticatedAreasRouteChildren {
  AuthenticatedAreasSlugRoute: typeof AuthenticatedAreasSlugRoute
  AuthenticatedAreasNovaRoute: typeof AuthenticatedAreasNovaRoute
}

const AuthenticatedAreasRouteChildren: AuthenticatedAreasRouteChildren = {
  AuthenticatedAreasSlugRoute: AuthenticatedAreasSlugRoute,
  AuthenticatedAreasNovaRoute: AuthenticatedAreasNovaRoute,
}

const AuthenticatedAreasRouteWithChildren =
  AuthenticatedAreasRoute._addFileChildren(AuthenticatedAreasRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRouteWithChildren
  AuthenticatedBuscaRoute: typeof AuthenticatedBuscaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandasRoute: typeof AuthenticatedDemandasRoute
  AuthenticatedProcessosRoute: typeof AuthenticatedProcessosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAreasRoute: AuthenticatedAreasRouteWithChildren,
  AuthenticatedBuscaRoute: AuthenticatedBuscaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandasRoute: AuthenticatedDemandasRoute,
  AuthenticatedProcessosRoute: AuthenticatedProcessosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
