/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProcessosRouteImport } from './routes/_authenticated/processos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedDemandasRouteImport } from './routes/_authenticated/demandas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBuscaRouteImport } from './routes/_authenticated/busca'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedProcessosIndexRouteImport } from './routes/_authenticated/processos.index'
import { Route as AuthenticatedDemandasIndexRouteImport } from './routes/_authenticated/demandas.index'
import { Route as AuthenticatedAreasIndexRouteImport } from './routes/_authenticated/areas.index'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated/processos.$id'
import { Route as AuthenticatedDemandasNovaRouteImport } from './routes/_authenticated/demandas.nova'
import { Route as AuthenticatedDemandasIdRouteImport } from './routes/_authenticated/demandas.$id'
import { Route as AuthenticatedAreasNovaRouteImport } from './routes/_authenticated/areas.nova'
import { Route as AuthenticatedAreasSlugRouteImport } from './routes/_authenticated/areas.$slug'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProcessosRoute = AuthenticatedProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandasRoute = AuthenticatedDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBuscaRoute = AuthenticatedBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcessosIndexRoute =
  AuthenticatedProcessosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProcessosRoute,
  } as any)
const AuthenticatedDemandasIndexRoute =
  AuthenticatedDemandasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDemandasRoute,
  } as any)
const AuthenticatedAreasIndexRoute = AuthenticatedAreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAreasRoute,
} as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProcessosRoute,
  } as any)
const AuthenticatedDemandasNovaRoute =
  AuthenticatedDemandasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedDemandasRoute,
  } as any)
const AuthenticatedDemandasIdRoute = AuthenticatedDemandasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDemandasRoute,
} as any)
const AuthenticatedAreasNovaRoute = AuthenticatedAreasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedAreasRoute,
} as any)
const AuthenticatedAreasSlugRoute = AuthenticatedAreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedAreasRoute,
} as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/areas': typeof AuthenticatedAreasRouteWithChildren
  '/busca': typeof AuthenticatedBuscaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/areas/$slug': typeof AuthenticatedAreasSlugRoute
  '/areas/nova': typeof AuthenticatedAreasNovaRoute
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/areas/': typeof AuthenticatedAreasIndexRoute
  '/demandas/': typeof AuthenticatedDemandasIndexRoute
  '/processos/': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/areas/$slug': typeof AuthenticatedAreasSlugRoute
  '/areas/nova': typeof AuthenticatedAreasNovaRoute
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/areas': typeof AuthenticatedAreasIndexRoute
  '/demandas': typeof AuthenticatedDemandasIndexRoute
  '/processos': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRouteWithChildren
  '/_authenticated/busca': typeof AuthenticatedBuscaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/areas/$slug': typeof AuthenticatedAreasSlugRoute
  '/_authenticated/areas/nova': typeof AuthenticatedAreasNovaRoute
  '/_authenticated/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/_authenticated/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/_authenticated/areas/': typeof AuthenticatedAreasIndexRoute
  '/_authenticated/demandas/': typeof AuthenticatedDemandasIndexRoute
  '/_authenticated/processos/': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/areas'
    | '/busca'
    | '/configuracoes'
    | '/dashboard'
    | '/demandas'
    | '/perfil'
    | '/processos'
    | '/admin/configuracoes'
    | '/areas/$slug'
    | '/areas/nova'
    | '/demandas/$id'
    | '/demandas/nova'
    | '/processos/$id'
    | '/areas/'
    | '/demandas/'
    | '/processos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/busca'
    | '/configuracoes'
    | '/dashboard'
    | '/perfil'
    | '/admin/configuracoes'
    | '/areas/$slug'
    | '/areas/nova'
    | '/demandas/$id'
    | '/demandas/nova'
    | '/processos/$id'
    | '/areas'
    | '/demandas'
    | '/processos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/areas'
    | '/_authenticated/busca'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/demandas'
    | '/_authenticated/perfil'
    | '/_authenticated/processos'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/areas/$slug'
    | '/_authenticated/areas/nova'
    | '/_authenticated/demandas/$id'
    | '/_authenticated/demandas/nova'
    | '/_authenticated/processos/$id'
    | '/_authenticated/areas/'
    | '/_authenticated/demandas/'
    | '/_authenticated/processos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/processos': {
      id: '/_authenticated/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof AuthenticatedProcessosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandas': {
      id: '/_authenticated/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AuthenticatedDemandasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/busca': {
      id: '/_authenticated/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof AuthenticatedBuscaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processos/': {
      id: '/_authenticated/processos/'
      path: '/'
      fullPath: '/processos/'
      preLoaderRoute: typeof AuthenticatedProcessosIndexRouteImport
      parentRoute: typeof AuthenticatedProcessosRoute
    }
    '/_authenticated/demandas/': {
      id: '/_authenticated/demandas/'
      path: '/'
      fullPath: '/demandas/'
      preLoaderRoute: typeof AuthenticatedDemandasIndexRouteImport
      parentRoute: typeof AuthenticatedDemandasRoute
    }
    '/_authenticated/areas/': {
      id: '/_authenticated/areas/'
      path: '/'
      fullPath: '/areas/'
      preLoaderRoute: typeof AuthenticatedAreasIndexRouteImport
      parentRoute: typeof AuthenticatedAreasRoute
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedProcessosRoute
    }
    '/_authenticated/demandas/nova': {
      id: '/_authenticated/demandas/nova'
      path: '/nova'
      fullPath: '/demandas/nova'
      preLoaderRoute: typeof AuthenticatedDemandasNovaRouteImport
      parentRoute: typeof AuthenticatedDemandasRoute
    }
    '/_authenticated/demandas/$id': {
      id: '/_authenticated/demandas/$id'
      path: '/$id'
      fullPath: '/demandas/$id'
      preLoaderRoute: typeof AuthenticatedDemandasIdRouteImport
      parentRoute: typeof AuthenticatedDemandasRoute
    }
    '/_authenticated/areas/nova': {
      id: '/_authenticated/areas/nova'
      path: '/nova'
      fullPath: '/areas/nova'
      preLoaderRoute: typeof AuthenticatedAreasNovaRouteImport
      parentRoute: typeof AuthenticatedAreasRoute
    }
    '/_authenticated/areas/$slug': {
      id: '/_authenticated/areas/$slug'
      path: '/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AuthenticatedAreasSlugRouteImport
      parentRoute: typeof AuthenticatedAreasRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAreasRouteChildren {
  AuthenticatedAreasSlugRoute: typeof AuthenticatedAreasSlugRoute
  AuthenticatedAreasNovaRoute: typeof AuthenticatedAreasNovaRoute
  AuthenticatedAreasIndexRoute: typeof AuthenticatedAreasIndexRoute
}

const AuthenticatedAreasRouteChildren: AuthenticatedAreasRouteChildren = {
  AuthenticatedAreasSlugRoute: AuthenticatedAreasSlugRoute,
  AuthenticatedAreasNovaRoute: AuthenticatedAreasNovaRoute,
  AuthenticatedAreasIndexRoute: AuthenticatedAreasIndexRoute,
}

const AuthenticatedAreasRouteWithChildren =
  AuthenticatedAreasRoute._addFileChildren(AuthenticatedAreasRouteChildren)

interface AuthenticatedDemandasRouteChildren {
  AuthenticatedDemandasIdRoute: typeof AuthenticatedDemandasIdRoute
  AuthenticatedDemandasNovaRoute: typeof AuthenticatedDemandasNovaRoute
  AuthenticatedDemandasIndexRoute: typeof AuthenticatedDemandasIndexRoute
}

const AuthenticatedDemandasRouteChildren: AuthenticatedDemandasRouteChildren = {
  AuthenticatedDemandasIdRoute: AuthenticatedDemandasIdRoute,
  AuthenticatedDemandasNovaRoute: AuthenticatedDemandasNovaRoute,
  AuthenticatedDemandasIndexRoute: AuthenticatedDemandasIndexRoute,
}

const AuthenticatedDemandasRouteWithChildren =
  AuthenticatedDemandasRoute._addFileChildren(
    AuthenticatedDemandasRouteChildren,
  )

interface AuthenticatedProcessosRouteChildren {
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
  AuthenticatedProcessosIndexRoute: typeof AuthenticatedProcessosIndexRoute
}

const AuthenticatedProcessosRouteChildren: AuthenticatedProcessosRouteChildren =
  {
    AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
    AuthenticatedProcessosIndexRoute: AuthenticatedProcessosIndexRoute,
  }

const AuthenticatedProcessosRouteWithChildren =
  AuthenticatedProcessosRoute._addFileChildren(
    AuthenticatedProcessosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRouteWithChildren
  AuthenticatedBuscaRoute: typeof AuthenticatedBuscaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandasRoute: typeof AuthenticatedDemandasRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProcessosRoute: typeof AuthenticatedProcessosRouteWithChildren
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAreasRoute: AuthenticatedAreasRouteWithChildren,
  AuthenticatedBuscaRoute: AuthenticatedBuscaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandasRoute: AuthenticatedDemandasRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProcessosRoute: AuthenticatedProcessosRouteWithChildren,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
